version: "3"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  webapp:
    depends_on:
      - mongodb
    image: oszura/webapp-prod:v1.1.1
    environment:
      - WEBAPP_MONGO_URI=mongodb://mongodb:27017
      - WEBAPP_HTTP_PORT=80
      - WEBAPP_CONFIG_PATH=/root/volume/webapp-config.json
    ports:
      - "80:80"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/config:/root/volume
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/public:/root/go/src/github.com/coda-it/gowebapp/public
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/views:/root/go/src/github.com/coda-it/gowebapp/views
