version: "3"
services:
  webapp:
    image: oszura/webapp-prod:v1.1.4
    environment:
      - WEBAPP_MONGO_URI=mongodb://mongodb:27017
      - WEBAPP_HTTP_PORT=80
      - WEBAPP_CONFIG="{\"apps\":[{\"id\":\"default\",\"modules\":[{\"id\":\"static\"},{\"id\":\"post\"},{\"id\":\"api-post\"},{\"id\":\"category\"},{\"id\":\"api-category\"},{\"id\":\"helpdesk\"},{\"id\":\"api-helpdesk\"},{\"id\":\"admin\"}],\"navigation\":[{\"id\":\"post\",\"label\":\"Posts\",\"href\":\"\/post\",\"isRoot\":false},{\"id\":\"category\",\"label\":\"Categories\",\"href\":\"\/category\",\"isRoot\":false},{\"id\":\"helpdesk\",\"label\":\"Helpdesk\",\"href\":\"\/helpdesk\",\"isRoot\":false},{\"id\":\"admin\",\"label\":\"Admin\",\"href\":\"\/admin\",\"isRoot\":true,\"children\":[{\"id\":\"admin-categories\",\"label\":\"Categories\",\"href\":\"\/admin\/categories\"},{\"id\":\"admin-add-category\",\"label\":\"Add Category\",\"href\":\"\/admin\/categories\/new\"},{\"id\":\"admin-posts\",\"label\":\"Posts\",\"href\":\"\/admin\/posts\"},{\"id\":\"admin-add-post\",\"label\":\"Add Post\",\"href\":\"\/admin\/posts\/new\"},{\"id\":\"admin-landing-page\",\"label\":\"Platform\",\"href\":\"\/admin\/platform\/edit\"}]}]}],\"defaultLanguage\":\"en\",\"certificate\":\"\",\"certificatePrivateKey\":\"\"}"
      - WEBAPP_MAILER_EMAIL=admin@localhost.pl
      - WEBAPP_MAILER_USERNAME=username6
      - WEBAPP_MAILER_PASSWORD=password123
      - WEBAPP_MAILER_SMTP_PORT=587
      - WEBAPP_MAILER_SMTP_AUTHURL=auth.mailingservice.com
    ports:
      - "80:80"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/config:/root/volume
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/public:/root/go/src/github.com/coda-it/gowebapp/public
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot/views:/root/go/src/github.com/coda-it/gowebapp/views
