version: "3"
services:
  mongodb:
    image: mongo:4.2.23
    ports:
      - "27017:27017"
  webapp:
    depends_on:
      - mongodb
    image: oszura/webapp-prod:v1.1.2
    environment:
      - WEBAPP_MONGO_URI=mongodb://mongodb:27017
      - WEBAPP_HTTP_PORT=80
      - WEBAPP_CONFIG_PATH=/root/volume/webapp-config.json
    ports:
      - "80:80"
