name: gowebapp

on:
  push:
    branches: [ CODA-277 ]

env:
  GO111MODULE: on
  APP_VERSION: v1.1.2

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Install dependencies
        run: make install
#      - name: Lint
#        run: make lint
      - name: Test
        run: make test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Install dependencies
        run: make install
      - name: Build application
        run: make all ENV=prod
      - name: Build docker image
        run: make image IMAGE_NAME=webapp ENV=prod V=$APP_VERSION
      - name: Publish docker image
        run: docker image push ${{ vars.DOCKER_LOGIN }}/webapp-prod:$APP_VERSION
